### ISSUE TITLE
Update for flathub

### ISSUE THREAD

**Issue by doctormo** [flathub/org.freedesktop.Tuhi#2]
The flathub image appears to be a bit old now, talking with an artist over on twitter here: https://twitter.com/realdoctormo/status/1518046914482249729

Speculation: Should we be building our own? It's quite hard to recommend tuhi with so few install options (apt/rpm/etc) but I think flatpak could work as a single format. I wonder if there's CI builders that could just do all this publishing work automatically.

**Comment by hfiguiere** [comment]
Which update? The only thing out of date is the runtime and this will be taken care of in #3. But otherwise 0.5 is the last tag.

**Comment by hfiguiere** [comment]
If you could test the build in #3 that would be very helpful. I don't have any hardware to test.

**Comment by doctormo** [comment]
Thanks, I wonder if upstream is waiting to make a release. They've had updates since early 2021, but I don't mean to pre-empt the process if tagging is what you're watching. Please feel free to close this one and I'll make a new issue with upstream tuhi

**Comment by whot** [comment]
/me enables all notifications on this repo...

**Comment by hfiguiere** [comment]
So #5 should have solved this, shouldn't it?

**Comment by doctormo** [comment]
Yes, thank you everyone!
